#!/usr/bin/env tsx
// Setup Environment Variables Helper Script
// Usage: npx tsx scripts/setup-env.ts

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { config } from 'dotenv';

config({ path: path.join(process.cwd(), '.env.local') });

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('🔧 IdeaMill - Environment Setup Helper\n');
  console.log('='.repeat(50));
  console.log('Script ini akan membantu Anda setup file .env.local\n');

  const envPath = path.join(process.cwd(), '.env.local');
  const envExists = fs.existsSync(envPath);

  if (envExists) {
    console.log('⚠️  File .env.local sudah ada!\n');
    const overwrite = await question('Apakah ingin overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n❌ Setup dibatalkan. File .env.local tidak diubah.');
      rl.close();
      return;
    }
  }

  console.log('\n📝 Silakan masukkan API keys Anda:\n');

  // OpenAI
  console.log('1️⃣  OpenAI API Key (WAJIB)');
  console.log('   Dapatkan di: https://platform.openai.com/api-keys');
  const openaiKey = await question('   Masukkan key (sk-proj-...): ');

  // Gemini
  console.log('\n2️⃣  Google Gemini API Key (OPSIONAL)');
  console.log('   Dapatkan di: https://aistudio.google.com/app/apikey');
  const geminiKey = await question('   Masukkan key (AIza...) atau tekan Enter untuk skip: ');

  // MongoDB
  console.log('\n3️⃣  MongoDB Configuration (WAJIB)');
  console.log('   Connection string untuk MongoDB (lokal atau Atlas)');
  console.log('   Contoh: mongodb://localhost:27017/ideamills');
  
  const mongoUri = await question('   MongoDB URI: ') || 'mongodb://localhost:27017/ideamills';
  const mongoDbName = await question('   Database Name [ideamills]: ') || 'ideamills';
  const mongoBucket = await question('   GridFS Bucket Name [images]: ') || 'images';

  // Generate .env.local
  const envContent = `# ===================================
# IdeaMill - Environment Variables
# ===================================
# Generated by setup-env.ts on ${new Date().toISOString()}

# ===================================
# OpenAI Configuration
# ===================================
OPENAI_API_KEY=${openaiKey}
OPENAI_EMBED_MODEL=text-embedding-3-small

# ===================================
# Google Gemini Configuration
# ===================================
${geminiKey ? `GEMINI_API_KEY=${geminiKey}` : '# GEMINI_API_KEY=your_gemini_api_key_here'}

# ===================================
# MongoDB Configuration
# ===================================
MONGODB_URI=${mongoUri}
MONGODB_DB=${mongoDbName}
MONGODB_BUCKET=${mongoBucket}

# ===================================
# CATATAN:
# ===================================
# - Queue berjalan di MongoDB
# - File ini (.env.local) sudah di-ignore oleh Git - aman!
# - Jangan commit file ini ke repository
# - Untuk production, set env variables di hosting dashboard
`;

  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ File .env.local berhasil dibuat!\n');
  console.log('📍 Lokasi:', envPath);
  rl.close();
}

main();
