#!/usr/bin/env tsx
// Setup Environment Variables Helper Script
// Usage: npx tsx scripts/setup-env.ts

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { config } from 'dotenv';

config({ path: path.join(process.cwd(), '.env.local') });

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('🔧 IdeaMills — Environment Setup Helper\n');
  console.log('='.repeat(50));
  console.log('Script ini akan membantu Anda setup file .env.local\n');

  const envPath = path.join(process.cwd(), '.env.local');
  const envExists = fs.existsSync(envPath);

  if (envExists) {
    console.log('⚠️  File .env.local sudah ada!\n');
    const overwrite = await question('Apakah ingin overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n❌ Setup dibatalkan. File .env.local tidak diubah.');
      rl.close();
      return;
    }
  }

  console.log('\n📝 Silakan masukkan API keys Anda:\n');

  // OpenRouter
  console.log('1️⃣  OpenRouter API Key (WAJIB)');
  console.log('   Untuk akses LLM (Gemini, Claude, GPT) — analyze foto + generate ide + prompt');
  console.log('   Dapatkan di: https://openrouter.ai/keys');
  const openrouterKey = await question('   Masukkan key (sk-or-v1-...): ');

  // useapi.net
  console.log('\n2️⃣  useapi.net Token (WAJIB)');
  console.log('   Untuk akses Google Flow (Veo video + Imagen image generation)');
  console.log('   Dapatkan di: https://useapi.net/dashboard');
  const useapiToken = await question('   Masukkan token: ');

  console.log('\n3️⃣  useapi.net Google Flow Email (WAJIB)');
  console.log('   Email akun Google Flow yang sudah di-link ke useapi.net');
  const useapiEmail = await question('   Masukkan email: ');

  // MongoDB
  console.log('\n4️⃣  MongoDB Configuration (WAJIB)');
  console.log('   Connection string untuk MongoDB (lokal atau Atlas)');
  console.log('   Contoh: mongodb://localhost:27017');
  const mongoUri = await question('   MongoDB URI [mongodb://localhost:27017]: ') || 'mongodb://localhost:27017';
  const mongoDbName = await question('   Database Name [ideamills]: ') || 'ideamills';
  const mongoBucket = await question('   GridFS Bucket Name [images]: ') || 'images';

  // Generate .env.local
  const envContent = `# ===================================
# IdeaMills - Environment Variables
# ===================================
# Generated by setup-env.ts on ${new Date().toISOString()}

# ===================================
# OpenRouter (LLM provider)
# ===================================
OPENROUTER_API_KEY=${openrouterKey}
OPENROUTER_REFERER=https://ideamills.app

# ===================================
# useapi.net (Google Flow: Veo video + Imagen image)
# ===================================
USEAPI_TOKEN=${useapiToken}
USEAPI_GOOGLE_EMAIL=${useapiEmail}

# ===================================
# MongoDB Configuration
# ===================================
MONGODB_URI=${mongoUri}
MONGODB_DB=${mongoDbName}
MONGODB_BUCKET=${mongoBucket}

# ===================================
# Storage path (default ./storage)
# ===================================
# STORAGE_PATH=./storage

# ===================================
# CATATAN:
# ===================================
# - Queue berjalan di MongoDB (collection JobQueue)
# - File ini (.env.local) sudah di-ignore oleh Git - aman!
# - Jangan commit file ini ke repository
# - Untuk production, set env variables di hosting dashboard
`;

  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ File .env.local berhasil dibuat!\n');
  console.log('📍 Lokasi:', envPath);
  console.log('\n📋 Next steps:');
  console.log('   1. Verifikasi config: npm run validate:env');
  console.log('   2. Start MongoDB lokal (kalau pakai local)');
  console.log('   3. Start app: ./start.sh');
  rl.close();
}

main().catch((err) => {
  console.error('❌ Error:', err);
  process.exit(1);
});
